tabsetPanel(
	tabPanel(title = "Data",
                       fluidRow(
		       column(1),
                       column(10,
		       h4("Select the data for which the clock and tree models will be assessed"),
                       fileInput("dataPath", label = h5(""), multiple = T),
		       br(),
		       h4("Select the format of your data"),
		       radioButtons("dataFormat", label = "",
                       choices = list("NEXUS" = "nexus", "Phylip" = "phylip", "FASTA" = "fasta"), selected = "nexus"),
		       br(),
		       h4("Select the file of posterior trees ('.trees') generated by BEAST"),
		       fileInput("treesPath", label = "", multiple = T),
		       br(),
		       h4("Select the file of posterior parameter values ('.log') generated by BEAST"),
		       fileInput("posteriorPath", label = "", multiple = T),
		       br(),
		       h4("Select the percentage of the posterior to be removed as burn-in"),
            	       numericInput("burnin", label = "", value = 10)
		       ),
		       column(1))
        ),
	tabPanel("Test statistics",
		       fluidRow(
		       column(1),
		       column(10,
		       tags$span(h4("Select test statistics for assessment"), tipify(bsButton("pB2", "?", style = "inverse", size = "extra-small"), placement = "right", "Test statistics are metrics used to compare empirical data with those generated under the model. They form the core of model assessment.")),
		       checkboxGroupInput("testStats", label = "",
		       choices = list("Stemminess  " = "stemmystat", "Df  " = "df", "Tree length  " = "trlen", "Imalance (req a non-fixed topology)  " = "imbal", "A-index (req a fixed topology)  " = "aindex", "Squared Mahalanobis distance  " = "maha"), selected = c("stemmystat", "df", "trlen", "maha")),
		       makeCheckboxTooltip(checkboxValue = "stemmystat", buttonLabel = "?", Tooltip = "To be added"),
                       makeCheckboxTooltip(checkboxValue = "df", buttonLabel = "?", Tooltip = "To be added"),
                       makeCheckboxTooltip(checkboxValue = "trlen", buttonLabel = "?", Tooltip = "To be added"),
                       makeCheckboxTooltip(checkboxValue = "imbal", buttonLabel = "?", Tooltip = "To be added"),
                       makeCheckboxTooltip(checkboxValue = "aindex", buttonLabel = "?", Tooltip = "To be added"),
                       makeCheckboxTooltip(checkboxValue = "maha", buttonLabel = "?", Tooltip = "To be added")
		       ),
		       column(1))
	),
	tabPanel("Output",
		       fluidRow(
                       column(1),
                       column(10,
		       h4("Select the output desired"),
		       checkboxGroupInput("whatToOutput", label = "",
                       choices = list("Individual locus metrics of adequacy" = "pvals", "Test plots" = "testPlots", "Only summary file (overrides other options)" = "simple", "Estimated clock-free tree for empirical data" = "phyloempres", "Simulated data" = "simdat", "Estimated clock-free trees for simulated data" = "phylosimres"), selected = c("pvals", "testPlots")),
		       br(),
		       h4("Select the format of the output data"),
		       radioButtons("outputFormat", label = "",
                       choices = list("NEXUS" = "nexus", "Phylip" = "phylip", "FASTA" = "fasta"), selected = "nexus"),
		       br(),
		       h4("Optional: Type the path of the output folder. The default is outputFolder in the main sofware folder"),
		       textInput("outputFolder", label = "", value = paste0(getwd(), "/../outputFolder/"))
		       ),
		       column(1))
	),
	tabPanel("Other options and START",
		       fluidRow(
                       column(1),
                       column(10,
		       h4("Select the number of simulations to be made"),
		       numericInput("Nsims", label = "",
                       value = 100),
		       br(),
		       h4("Select the number of computer cores to be used"),
		       numericInput("Ncores", label = h5("Multi-core assessments can only be aborted at the completion of a locus assessment"),
                       value = 1),
		       br(),
                       checkboxInput("overwrite", label = h5("Overwrite previous analyses"), value = FALSE),
		       br(),
		       actionButton("startAnalysis", label = "START ASSESSMENT")
		       ),
		       column(1))
	)
	
)
