tabsetPanel(
	tabPanel("Data",
                       fluidRow(
		       column(1),
                       column(10,
		       h4("Select the data for which the clock and tree models will be assessed"),
                       fileInput("dataPath", label = h5(""), multiple = T),
		       br(),
		       radioButtons("dataFormat", label = h4("Select the format of your data"),
                       choices = list("NEXUS" = "nexus", "Phylip" = "phylip", "FASTA" = "fasta"), selected = "nexus"),
		       br(),
		       fileInput("treesPath", label = h4("Select the file of posterior trees generated by BEAST"), multiple = T),
		       br(),
		       fileInput("posteriorPath", label = h4("Select the file of posterior parameter values generated by BEAST"), multiple = T),
		       br(),
            	       numericInput("burnin", label = h4("Select the percentage of the posterior to be removed as burn-in"), value = 10)
		       ),
		       column(1))
        ),
	tabPanel("Test statistics",
		       fluidRow(
		       column(1),
		       column(10,
		       checkboxGroupInput("testStats", label = h4("Select test statistics for assessment"),
		       choices = list("Stemminess" = "stemmystat", "Df" = "df", "Tree length" = "trlen", "Imbalance (requires a non-fixed tree topology)" = "imbal", "A-index (requires a fixed tree topology)" = "aindex", "Squared Mahalanobis distance" = "maha"), selected = c("stemmystat", "df", "trlen", "maha")),
		       p("Only select the Mahalanobis distance if multiple other statistics are also selected.")
		       ),
		       column(1))
	),
	tabPanel("Output",
		       fluidRow(
                       column(1),
                       column(10,
		       checkboxGroupInput("whatToOutput", label = h4("Select the output desired"),
                       choices = list("Only summary file (overrides other options)" = "simple", "Individual locus metrics of adequacy" = "pvals", "Estimated clock-free tree for empirical data" = "phyloempres", "Simulated data" = "simdat", "Estimated clock-free trees for simulated data" = "phylosimres", "Test plots" = "testPlots"), selected = c("pvals", "testPlots")),
		       br(),
		       radioButtons("outputFormat", label = h4("Select the format of the output data"),
                       choices = list("NEXUS" = "nexus", "Phylip" = "phylip", "FASTA" = "fasta"), selected = "nexus"),
		       br(),
		       textInput("outputFolder", label = h4("Optional: Type the path of the output folder. The default is outputFolder in the main sofware folder"), value = paste0(getwd(), "/../outputFolder/"))
		       ),
		       column(1))
	),
	tabPanel("Other options and START",
		       fluidRow(
                       column(1),
                       column(10,
		       numericInput("Nsims", label = h4("Select the number of simulations to be made"),
                       value = 100),
		       br(),
		       h4("Select the number of computer cores to be used"),
		       numericInput("Ncores", label = h5("Multi-core assessments can only be aborted at the completion of a locus assessment"),
                       value = 1),
		       br(),
                       checkboxInput("overwrite", label = h5("Overwrite previous analyses"), value = FALSE),
		       br(),
		       actionButton("startAnalysis", label = "START ASSESSMENT")
		       ),
		       column(1))
	)
	
)
